---
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ .Values.mas_instance_id }}-pipelines
  annotations:
    "helm.sh/hook": "post-delete"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mas-undeploy-sync-role
  generateName: "mas-undeploy-sync-role-"
  namespace: mas-{{ .Values.mas_instance_id }}-pipelines
  annotations:
    checkov.io/skip1: CKV_K8S_20
    checkov.io/skip2: CKV_K8S_37
    checkov.io/skip3: CKV_K8S_40
    checkov.io/skip4: CKV_K8S_35
    checkov.io/skip5: CKV_K8S_43
    checkov.io/skip6: CKV_K8S_38
    checkov.io/skip7: CKV_K8S_13
    checkov.io/skip8: CKV_K8S_11
    checkov.io/skip9: CKV_K8S_10
    checkov.io/skip10: CKV_K8S_29
    checkov.io/skip11: CKV_K8S_28
    checkov.io/skip12: CKV_K8S_31
    checkov.io/skip13: CKV_K8S_30
    checkov.io/skip14: CKV_K8S_12
    checkov.io/skip15: CKV_K8S_23
    checkov.io/skip16: CKV_K8S_22
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        app: "mas-deploy-job"
    spec:
      volumes:
        #- name: pv-storage
        #  persistentVolumeClaim:
        #    claimName: config-pvc
      containers:
        - name: mas-deploy
          image: quay.io/ibmmas/cli:7.18.0-pre.master
          imagePullPolicy: Always
          #volumeMounts:
          #  - mountPath: "/usr/config-pvc"
          #    name: pv-storage
          command:
            - /bin/sh
            - -c
            - |


              set -e

              echo "MAS_INSTANCE_ID=${MAS_INSTANCE_ID}"

                echo "Uninstallation started"

                mas uninstall -i "${MAS_INSTANCE_ID}" --no-confirm

          env:
            - name: MAS_INSTANCE_ID
              value: "{{ .Values.mas_instance_id }}"

      restartPolicy: Never
      serviceAccountName: sync-sa
  backoffLimit: 6
